### ISSUE TITLE
Plans to CKEditor 5?

### ISSUE THREAD

**Issue by abreulima** [helloflask/flask-ckeditor#39]
Since CKEditor 5 is released. Is there any plan to it be implemented on Flask CKEditor?

**Comment by greyli** [comment]
Not have the plan yet, since CKEditor 5 comes with a new API, this may need a lot of work. BTW, if someone wants to make the first step, feel free to fire a PR.

**Comment by greyli** [comment]
Since CKEditor has changed the license to GPL, we decided not to add support to CKEditor 5. Thanks!
