### ISSUE TITLE
Documentation not available 

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/flask-ckeditor#58]
https://flask-ckeditor.readthedocs.io/ only shows an error.

500 Internal Server Error
nginx

Please fix this

**Comment by rpmzandwijk** [comment]
It appears to be a global issue on the readthedocs website. Other parts of the site also do not work. That is not something we can fix ourselves, we’ll have to wait until readthedocs fixed the issue.

**Comment by rpmzandwijk** [comment]
Readthedocs is using Cloudflare and Cloudflare is experiencing issues at the moment. Other sites are not working too.

**Comment by rpmzandwijk** [comment]
The cloudflare issue is fixed, closing this issue.
