### ISSUE TITLE
Markup removed in Flask 3.0.0

### ISSUE THREAD

**Issue by jmroche** [helloflask/flask-ckeditor#67]
When upgrading Flask and Werkzeug to version 3.0.0 Flask-CKEditor brakes the application as Markup has been removed from Flask as documented in PR 5223 (https://github.com/pallets/flask/pull/5223). 

On flask_ckeditor __init__.py line 12: 

`from flask import current_app, Markup, Blueprint, url_for, request, jsonify, render_template_string`

should be updated to import Markup from MarkupSafe

`from markupsafe import Markup`

**Comment by mdsanuarmahmud** [comment]
facing this issue 

from flask import current_app, Markup, Blueprint, url_for, request, jsonify, render_template_string 
ImportError: cannot import name 'Markup' from 'flask' (C:\Users\HP\AppData\Roaming\Python\Python311\site-packages\flask\__init__.py)

**Comment by greyli** [comment]
Fixed in #68 and released 0.5.0. Thanks.
