### ISSUE TITLE
there is no static folder in pypi package 0.5.1

### ISSUE THREAD

**Issue by JonahZeng** [helloflask/flask-ckeditor#82]
thanks for your work, it helps me a lot.
when I use pip install flask-ckeditor， I found there is no static folder in Lib/site-packages/flask_ckeditor，so it doesn't work when I set CKEDITOR_SERVE_LOCAL=True. for chinese developer, cdn.ckeditor.com is blocked by GFW，so ckeditor.load() will fail by default setting CKEDITOR_SERVE_LOCAL=False.

**Comment by greyli** [comment]
Fixed in the 1.0.0 version, please try to update it with:

```
pip install -U flask-ckeditor
```

Thanks!
