### ISSUE TITLE
Warning CKEditor 4.14.0 version is not secure

### ISSUE THREAD

**Issue by localhostPIB** [helloflask/flask-ckeditor#83]
I get the message:" This Consider upgrading to the latest one, 4.24.0-lts." 

![editor](https://github.com/helloflask/flask-ckeditor/assets/25406100/fac13acf-922c-4af3-bf9a-497fa3e479aa)

How to upgrade this version ?

**Comment by crlandwe** [comment]
+1, you can hide it with css.

**Comment by AleksaPetrovicRBT** [comment]
Hello, indeed you can hide it with CSS, but is this the right solution? In my humble opinion, we should (always) aim for the best and secure libraries. This is what is suggested in the [release notes](https://ckeditor.com/cke4/release-notes) by CKEditor. Can you please let me know whether Flask CKEditor has a plan to fix this and what is the ETA?

**Comment by localhostPIB** [comment]
> +1, you can hide it with css.

You can hide it, but the (potential security) problem remains

**Comment by crlandwe** [comment]
> You can hide it, but the (potential security) problem remains

I obviously agree with this, hence the bump and making myself part of the conversation. This feature was first requested in 2020, and here we are in 2024. I suggested this as a band-aid, because I would have hoards of users submitting support tickets about this.

**Comment by localhostPIB** [comment]
> > You can hide it, but the (potential security) problem remains
> 
> I obviously agree with this, hence the bump and making myself part of the conversation. This feature was first requested in 2020, and here we are in 2024. I suggested this as a band-aid, because I would have hoards of users submitting support tickets about this.

It's certainly not wrong as a quick emergency solution, but I hope that there will be a solution that will satisfy us all.

**Comment by remyzandwijk** [comment]
When using the CDN (meaning: not loading the CKEditor resources from a local location), it should be possible to override the version by using this in the templates:

`{{ ckeditor.load(version='4.24.0-lts') }}`

I guess it would be better to have something like `app.config['CKEDITOR_VERSION'] = '4.24.0-lts'`, but that's not the case right now.

**Comment by localhostPIB** [comment]
> When using the CDN (meaning: not loading the CKEditor resources from a local location), it should be possible to override the version by using this in the templates:
> 
> `{{ ckeditor.load(version='4.24.0-lts') }}`
> 
> I guess it would be better to have something like `app.config['CKEDITOR_VERSION'] = '4.24.0-lts'`, but that's not the case right now.

The idea is good, but now there's probably a paid version:

[CKEDITOR]: The license key is missing or invalid.

If you suddenly started to see this message, this may mean you accidentally updated CKEditor 4 to the LTS version (4.23.0 and above). This version of the editor is under commercial terms and requires acquiring an "Extended Support Model" contract - https://ckeditor.com/ckeditor-4-support/

For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#invalid-lts-license-key

**Comment by remyzandwijk** [comment]
Right, I was unaware of that. The latest non-LTS version seems to be 4.22.1, released on June 30th 2023. That version has the security issue found in January 2024 I think, so that's not an option.

**Comment by localhostPIB** [comment]
When I want to include CKEditor 5 I get the following message on my Browser: 

> "Uncaught SyntaxError: export declarations may only appear at top level of a module".

This is how I integrated it:

`{{ ckeditor.load(custom_url=url_for('static', filename='/js/lib/ckeditor5.js')) }}`

**Comment by greyli** [comment]
You can [disable the version check](https://github.com/django-ckeditor/django-ckeditor/issues/761#issuecomment-1932705710) with `custom_config `option like this:

```
{{ ckeditor.config(name='body', custom_config="versionCheck: false") }}
```

I will default this option to `false` in the next fix release, similar to [what Django-CKEditor did](https://github.com/django-ckeditor/django-ckeditor/blob/b71c85be2974d8bca0ee8562cf2fcaacca8e8749/ckeditor/widgets.py#L129).

A permanent fix would be upgrading to CKEditor 5, which is currently unsupported. Since CKEditor 5 has changed the license to GPL, I don't think we will move to CKEditor 5.

**Comment by ai-abdellah** [comment]
even the version 4.22.1 is not secure.

![2024-07-04 15 05 23 192 168 235 129 a03b5c81e575](https://github.com/helloflask/flask-ckeditor/assets/7944733/61347c41-a0e2-4bf6-870b-92a8ae92ca91)

**Comment by greyli** [comment]
In the [1.0.0 version](https://github.com/helloflask/flask-ckeditor/releases/tag/1.0.0), the version check has been disabled.

**Comment by skwzrd** [comment]
Getting CkEditor 4.24 making POSTs to server endpoint with the codesnippet plugin, resulting in 405 - method not allowed.

**Comment by winds1983** [comment]
<img width="749" height="314" alt="Image" src="https://github.com/user-attachments/assets/ae211f96-dab9-4b3f-bdcc-0523231a5803" />

when I upgraded to 1.0.0, but the new notes still showed up.
This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.25.1-lts.
Can you make a small upgrade for this? @greyli
